image:
  file: .gitpod.Dockerfile
ports:
  - port: 9888
    onOpen: open-browser
tasks:
  - init: |
      npm ci
      npm run server:init
    command: |
      gp sync-done init
      export NODE_ENV=development
      export VSCODE_DEV=1
      npm run watch
    name: watch app
  - command: |
      export NODE_ENV=development
      export VSCODE_DEV=1
      gp sync-await init
      ./scripts/code-server.sh  --without-connection-token
    name: run app
    openMode: split-right
github:
  prebuilds:
    branches: true
    pullRequestsFromForks: true
vscode:
  extensions:
    - dbaeumer.vscode-eslint
